import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavBar from "../../components/NavBar";

export const metadata: Metadata = {
  title: "Sorteos App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar />
      <div className="flex justify-center w-full">
        <div className="max-w-7xl">{children}</div>
      </div>
    </>
  );
}
